dataset:
  name: gtsrb
  path: data/processed/gtsrb
  num_classes: 43
  known_classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  unknown_classes:
  - 40
  - 41
  - 42
  num_known_classes: 40
  img_size: 64
  batch_size: 64
  num_workers: 4
  class_names:
    0: Speed limit (20km/h)
    1: Speed limit (30km/h)
    2: Speed limit (50km/h)
    3: Speed limit (60km/h)
    4: Speed limit (70km/h)
    5: Speed limit (80km/h)
    6: End of speed limit (80km/h)
    7: Speed limit (100km/h)
    8: Speed limit (120km/h)
    9: No passing
    10: No passing for vehicles over 3.5 metric tons
    11: Right-of-way at the next intersection
    12: Priority road
    13: Yield
    14: Stop
    15: No vehicles
    16: Vehicles over 3.5 metric tons prohibited
    17: No entry
    18: General caution
    19: Dangerous curve to the left
    20: Dangerous curve to the right
    21: Double curve
    22: Bumpy road
    23: Slippery road
    24: Road narrows on the right
    25: Road work
    26: Traffic signals
    27: Pedestrians
    28: Children crossing
    29: Bicycles crossing
    30: Beware of ice/snow
    31: Wild animals crossing
    32: End of all speed and passing limits
    33: Turn right ahead
    34: Turn left ahead
    35: Ahead only
    36: Go straight or right
    37: Go straight or left
    38: Keep right
    39: Keep left
    40: Roundabout mandatory
    41: End of no passing
    42: End of no passing by vehicles over 3.5 metric tons
model:
  type: resnet50_energy
  d_embed: 512
  backbone:
    name: resnet50
    pretrained: true
    frozen: false
    num_output_features: 2048
  neck:
    in_features: 2048
    out_features: 512
    use_batchnorm: true
    use_relu: true
  cls_head:
    in_features: 512
    use_weight_norm: true
    label_smoothing: 0.1
    temperature: 1.0
  osr_head:
    type: energy
    in_features: 512
train:
  optimizer:
    name: AdamW
    lr: 0.0005
    weight_decay: 1.0e-05
  scheduler:
    name: CosineAnnealingLR
    params:
      T_max: 50
  trainer:
    max_epochs: 50
    gpus: 1
    precision: 32
  loss:
    ce_seen_weight: 1.0
  calibration:
    method: temperature_scaling
    val_fraction_for_calibration: 0.2
eval:
  run_id: 2025-06-04_18-46-39
  checkpoint_path: null
  batch_size: 256
  save_scores: true
  save_features_for_tsne: true
seed: 42
outputs_root_dir: outputs
data_root_dir: data/processed
