name: cifar10
path: ${data_root_dir}/cifar10 # torchvision will download here
num_classes: 8
num_known_classes: 8
total_original_classes: 10
known_classes_original_ids: [0, 1, 2, 3, 4, 5, 6, 7]
unknown_classes_original_ids: [8, 9]
num_workers: 4

# Augmentations
img_size: 32
batch_size: 128