name: gtsrb
path: ${data_root_dir}/gtsrb # GTSRB will be downloaded here
num_classes: 34 # Number of known classes (model output = num_known_classes)
num_known_classes: 34
total_original_classes: 43
# Known classes: First 34 classes (0-33)
known_classes_original_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]
# Unknown classes: Last 9 classes (34-42)
unknown_classes_original_ids: [34, 35, 36, 37, 38, 39, 40, 41, 42]
num_workers: 4
img_size: 64 # Target image size after resizing

# Augmentations
train_augmentations:
  - name: RandomCrop
    params:
      size: [64, 64]
      padding: 4
  - name: RandomHorizontalFlip
    params:
      p: 0.5
  - name: ColorJitter
    params:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
  - name: ToTensor
  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406] # ImageNet mean
      std: [0.229, 0.224, 0.225]  # ImageNet std

val_augmentations:
  - name: Resize
    params:
      size: [64, 64]
  - name: ToTensor
  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

test_augmentations:
  - name: Resize
    params:
      size: [64, 64]
  - name: ToTensor
  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
