name: gtsrb
path: ${data_root_dir}/gtsrb # GTSRB will be downloaded here
num_classes: 40
num_known_classes: 40
total_original_classes: 43
known_classes_original_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
unknown_classes_original_ids: [40, 41, 42]
num_workers: 4

# Augmentations
train_augmentations:
  - RandomCrop:
      size: [64, 64]
      padding: 4
  - RandomHorizontalFlip:
      p: 0.5
  - ColorJitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
  - ToTensor:
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_augmentations:
  - Resize:
      size: [64, 64]
  - ToTensor:
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]