# Experiment 7: GTSRB with Threshold-based NLL Loss (3 unknown classes)
# Testing confidence thresholding approach on GTSRB
defaults:
  - dataset: gtsrb_3u
  - model: resnet50_enhanced
  - train: enhanced_base
  - eval: base
  - _self_

dataset:
  name: gtsrb
  path: ./data
  img_size: 32
  num_classes: 40  # 40 known classes
  num_known_classes: 40
  total_original_classes: 43
  known_classes_original_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]  # 40 known
  unknown_classes_original_ids: [40, 41, 42]  # 3 unknown
  batch_size: 128
  num_workers: 4
  val_split_ratio: 0.2

model:
  type: "enhanced_openset_resnet50"
  d_embed: 512

  backbone:
    name: "resnet50"
    pretrained: True
    frozen: False
    num_output_features: 2048

  neck:
    enabled: False  # No neck for this experiment
    
  cls_head:
    in_features: ${model.backbone.num_output_features}
    use_weight_norm: True
    label_smoothing: 0.1
    temperature: 1.0

train:
  optimizer:
    name: "AdamW"
    lr: 0.0005  # Lower learning rate for GTSRB
    weight_decay: 0.01

  scheduler:
    name: "CosineAnnealingLR"
    params:
      T_max: 50

  trainer:
    max_epochs: 50
    gpus: 1
    precision: 32
    deterministic: True

  loss:
    strategy: "threshold"  # Use thresholding approach
    confidence_threshold: 0.6  # Threshold parameter
    dummy_class_penalty: 1.8   # Penalty multiplier
    ce_seen_weight: 1.0
    use_dummy_class: False

  calibration:
    method: "temperature_scaling"

  run_test_after_train: True
  run_custom_evaluation_after_train: True

seed: 42
outputs_root_dir: "outputs"
data_root_dir: "data/processed"

# Experiment identifier
experiment_name: "gtsrb_threshold_3u_no_neck"
